Add Solin to Showcase
remix-run/remix-website pull request #255
Opened 2024-04-30 21:51 UTC by ParkerMJones

Sharing what we do with Remix ❤️

https://www.solin.stream/

2024-05-24 14:57 UTC, sergiodxa approved these changes

2024-05-24 15:10 UTC, brookslybrand requested changes
@ParkerMJones you just want to put a bunch of thirst traps on our website! This is not the way we're gonna sell Remix 😉 

Jokes aside, thanks for the PR. The website is very nice. Sorry I've taken so long to review!

My only request is that you re-record the preview so that there aren't white margin's on the sides

<img width="776" alt="image" src="https://github.com/remix-run/remix-website/assets/12396812/12f5793f-8531-48a8-9dbd-0f00f8b75f27">

2024-05-24 20:15 UTC, ParkerMJones commented
@brookslybrand someone needs to show how _sexy_ Remix can be! Re-recorded with a resolution to match the others, let me know if this matches what you're looking for.

2024-05-28 15:50 UTC, brookslybrand commented on data/showcase.yaml
> +  description: "The world's largest marketplace for fitness challenges from creators."
```suggestion
  description: "The world's largest marketplace for fitness challenges from creators"
```

2024-05-28 15:51 UTC, merged